data = read.table('household_power_consumption.txt', sep=";", header=T, stringsAsFactors= F)
data1 = data[data$Date %in% c('1/2/2007', '2/2/2007'),]
data1$DateTime = strptime(paste(data1$Date, data1$Time), format = "%d/%m/%Y %H:%M:%S")
png(filename = 'plot4.png')
par(mfrow = c(2,2))
plot(data1$DateTime, data1$Global_active_power, type = 'n', ylab = 'Global Active Power (kilowatts)', xlab = " ")
lines(data1$DateTime, data1$Global_active_power)
plot(data1$DateTime, data1$Voltage, type='n', ylab = 'Voltage', xlab = " ")
lines(data1$DateTime, data1$Voltage)
plot(data1$DateTime,data1$Sub_metering_1, type='n', ylab = 'Energy sub metering', xlab = " ")
lines(data1$DateTime,data1$Sub_metering_1)
lines(data1$DateTime,data1$Sub_metering_2, col='red')
lines(data1$DateTime,data1$Sub_metering_3, col='blue')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = c(1,1,1), col = c('black', 'red', 'blue'))
with(data1, plot(DateTime, Global_reactive_power, type='n', xlab = 'datetime'))
lines(data1$DateTime,data1$Global_reactive_power)
dev.off()